version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8888:80
    depends_on:
      - app
    container_name: project_nginx
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: project_app
    networks:
      - laravel
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8110:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db
    networks:
      - laravel
  adminer:
    image: adminer
    restart: always
    ports:
        - 6080:8080
    networks:
      - laravel
  node:
    image: node:20-alpine
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    tty: true
    ports:
          - "1222:3000"
    container_name: project_node
    networks:
      - laravel

